# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0004_auto_20170221_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slider',
            field=models.ImageField(upload_to=''),
        ),
    ]
