# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0005_auto_20170222_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider_photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slider',
            field=models.BooleanField(),
        ),
    ]
