# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'New', b'New'), (b'In process', b'In process'), (b'Ready to deliver', b'Ready to deliver'), (b'Delivering', b'Delivering'), (b'Delivered', b'Delivered'), (b'Suspended', b'Suspended'), (b'Cancelled', b'Cancelled')], default=b'New', max_length=15),
        ),
    ]
