# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0002_auto_20170124_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In process', 'In process'), ('Ready to deliver', 'Ready to deliver'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
    ]
