# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0003_auto_20170207_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_enabled',
            new_name='in_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='on_main_page',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_really_hot',
            new_name='slider',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
