# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0007_auto_20170224_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='/static/upload/'),
        ),
    ]
